const list = [
  {
    id: 1,
    title: "My first book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/51wZPYvtPGL._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 2,
    title: "My second book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/61j1rJbYbKS._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 3,
    title: "My first book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/51wZPYvtPGL._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 4,
    title: "My second book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/61j1rJbYbKS._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 5,
    title: "My first book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/51wZPYvtPGL._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 6,
    title: "My second book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/61j1rJbYbKS._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 7,
    title: "My first book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/51wZPYvtPGL._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 8,
    title: "My second book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/61j1rJbYbKS._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 9,
    title: "My first book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/51wZPYvtPGL._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 10,
    title: "My second book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/61j1rJbYbKS._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 11,
    title: "My first book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/51wZPYvtPGL._SY445_SX342_.jpg",
    amount: 1,
  },
  {
    id: 12,
    title: "My second book of pencil control",
    author: "by wonder house books",
    price: 89,
    img: "https://m.media-amazon.com/images/I/61j1rJbYbKS._SY445_SX342_.jpg",
    amount: 1,
  }
];